services:
  - type: web
    name: event-monolith-app
    env: node
    plan: free
    buildCommand: |
  curl -fsSL https://bun.sh/install | bash
  export BUN_INSTALL="/opt/render/.bun"
  export PATH="$BUN_INSTALL/bin:$PATH"
  bun install
  bunx prisma generate
startCommand: bun run src/index.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true